/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MimicRouteImport } from './routes/mimic'
import { Route as EmblemRouteImport } from './routes/emblem'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as IndexRouteImport } from './routes/index'

const MimicRoute = MimicRouteImport.update({
  id: '/mimic',
  path: '/mimic',
  getParentRoute: () => rootRouteImport,
} as any)
const EmblemRoute = EmblemRouteImport.update({
  id: '/emblem',
  path: '/emblem',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/emblem': typeof EmblemRoute
  '/mimic': typeof MimicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/emblem': typeof EmblemRoute
  '/mimic': typeof MimicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/emblem': typeof EmblemRoute
  '/mimic': typeof MimicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atlas' | '/emblem' | '/mimic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atlas' | '/emblem' | '/mimic'
  id: '__root__' | '/' | '/atlas' | '/emblem' | '/mimic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  EmblemRoute: typeof EmblemRoute
  MimicRoute: typeof MimicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mimic': {
      id: '/mimic'
      path: '/mimic'
      fullPath: '/mimic'
      preLoaderRoute: typeof MimicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emblem': {
      id: '/emblem'
      path: '/emblem'
      fullPath: '/emblem'
      preLoaderRoute: typeof EmblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  EmblemRoute: EmblemRoute,
  MimicRoute: MimicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
